#!/usr/bin/perl
use CGI;
use DBI;
$hostname="localhost";
$username="u20180571";
$password="zgW8kbjv";
$database="u20180571";
$dsn="DBI:mysql:database=$database;host=$hostname;port=$port";
$dbh=DBI->connect($dsn,$username,$password);

$sth=$dbh->prepare("select ID,DNI,Nombres,Paterno,Materno,Nacimiento,Estado from clients");
$sth->execute();
print "Content-type:text/html\n\n";
print "<!DOCTYPE html>\n";
print "<html><head><title>Editar Clientes</title>\n";
print "<link rel='stylesheet' href='../css/bankStyle.css'></head>\n";
print "<body>\n";
print "<div class='c'>\n";
print "<div class='c1'>\n";
print "<h1>Editar Clientes</h1>\n";
print "<form action='editClients2.pl'>\n";
print "<select onChange='fillValues()' id='client_id' name='select'>\n";
while(@clients=$sth->fetchrow_array()){
	print "<option value=\"$clients[0],$clients[1],$clients[2],$clients[3],$clients[4],$clients[5],$clients[6]\">$clients[2] $clients[3] $clients[4]</option>\n";
}
print "</select><br>\n";
print "<input type='hidden' id='id' name='id'>";
print "<input id='name' name='name'><br>\n";
print "<input id='dni' name='dni'><br>\n";
print "<input id='paterno' name='paterno'><br>\n";
print "<input id='materno' name='materno'><br>\n";
print "<input id='nacimiento' type='date' name='nacimiento'><br>\n";
print "<input id='estado' name='estado'><br>\n"; 
print "<input type='submit' value='Guardar cambios'><br>\n";
print "<input type='button' value='Deshacer cambios' onClick='fillValues()'><br>\n";
print "</form>\n";
print "</div>\n";
print "</div>\n";
print "</body>\n";
print "<script>";
print "function fillValues(){\n";
print "var arr=[6];";
print "var data=document.getElementById('client_id').value;\n";
print "for(var i=0;i<7;i++){";
print "var index=data.indexOf(',');";
print "if(index!=-1){";
print "arr[i]=data.substring(0,index);";
print "data=data.substring(index+1,data.length);";
print "}else{";
print "arr[i]=data}";
print "document.getElementById('id').value=arr[0];\n";
print "document.getElementById('dni').value=arr[1];\n";
print "document.getElementById('name').value=arr[2];\n";
print "document.getElementById('paterno').value=arr[3];\n";
print "document.getElementById('materno').value=arr[4];\n";
print "document.getElementById('nacimiento').value=arr[5];\n";
print "document.getElementById('estado').value=arr[6];\n";
print "}";
print "}\n";
print "fillValues();";
print "</script>\n";
print "</html>";
